name: Run simple test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    name: Test ${{ matrix.test }}
    strategy:
      fail-fast: false
      matrix:
        test: [simple]
    uses: ./.github/workflows/test_single.yml
    with:
      test: ${{ matrix.test }}